# Run Mode: local or browserstack
# Change this value to switch between local emulator and BrowserStack
# Options: "local" or "browserstack"
runMode=local

# Local Appium Configuration
appium.server.url=http://127.0.0.1:4723/wd/hub
platformName=Android
deviceName=emulator-5554
platformVersion=16
appPackage=com.raising.prodigy
appActivity=com.raising.prodigy.MainActivity

# BrowserStack Configuration (read from browserstack.yml)
# userName and accessKey are in browserstack.yml

# Environment Configuration
ENV=staging
STAGING_APP=/Users/abcom/Downloads/Stagging_app-release.apk
PROD_APP=/Users/abcom/Downloads/Production_app-release.apk

